### ISSUE TITLE
undefined method `baseurl' for Chef::Resource::YumRepository

### ISSUE THREAD

**Issue by keithbmcd** [aporat/php55-cookbook#5]
Hi,

We have some problems when using this cookbook.
# 
# Error executing action `run` on resource 'ruby_block[Compile Custom OpsWorks Run List]'
## NoMethodError

undefined method `baseurl' for Chef::Resource::YumRepository
## Resource Declaration:
# In /opt/aws/opsworks/releases/20150423171152_24100020150423171152/cookbooks/opsworks_custom_cookbooks/recipes/execute.rb

3: ruby_block("Compile Custom OpsWorks Run List") do
4:   block do
5:     begin
6: 
7:       # Reload cookbooks after they're available on local filesystem
8:       cl = Chef::CookbookLoader.new(Chef::Config[:cookbook_path])
9:       cl.load_cookbooks
10:       self.run_context.instance_variable_set(:@cookbook_collection, Chef::CookbookCollection.new(cl))
11: 
12:       # Expand run list with custom cookbooks and load them into the current run_context
13:       opsworks_run_list = Chef::RunList.new(*node[:opsworks_custom_cookbooks][:recipes])
14:       Chef::Log.info "New Run List expands to #{opsworks_run_list.run_list_items.map(&:name).inspect}"
15:       self.run_context.load(opsworks_run_list)
16: 
17:     rescue Exception => e
18:       Chef::Log.error "Caught exception while compiling OpsWorks custom run list: #{e.class} - #{e.message} - #{e.backtrace.join("\n")}"
19:       raise e
20:     end
21: 
22:   end
23: end
## Compiled Resource:
# Declared in /opt/aws/opsworks/releases/20150423171152_24100020150423171152/cookbooks/opsworks_custom_cookbooks/recipes/execute.rb:3:in `from_file'

ruby_block("Compile Custom OpsWorks Run List") do
retry_delay 2
cookbook_name :opsworks_custom_cookbooks
recipe_name "execute"
block_name "Compile Custom OpsWorks Run List"
retries 0
block #Proc:0x00007f158156aa48@/opt/aws/opsworks/releases/20150423171152_24100020150423171152/cookbooks/opsworks_custom_cookbooks/recipes/execute.rb:4
action "run"
end

May I know how to fix it?

Thanks

Keith

**Comment by aporat** [comment]
I am no longer using this cookbook, so im not quite sure what's the issue.

If you're looking to integrate php 5.5 / 5.6 into opsworks, I suggest you look at https://github.com/aporat/opsworks-php55-app-layer-cookbooks. it provides php setup, configure and deployment.

**Comment by keithbmcd** [comment]
thanks, I will try it
